### ISSUE TITLE
抄作业的功能如何使用，已经做好了吗？

### ISSUE THREAD

**Issue by wangyishenga** [AegirTech/ArkLights#100]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**抄作业的功能如何使用，已经做好了吗？
请尽可能详细的描述问题

**复现步骤(必填)**
复现此问题的详细步骤

**期望的行为**
正常的情况下程序应该如何运作

**截图**
请添加相关的截图

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 
 - 更新时间: 

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
#93

**Comment by wangyishenga** [comment]
> #93
![Screenshot_20240506-224337](https://github.com/AegirTech/ArkLights/assets/87552769/45cf827b-1221-4dff-9c22-31c66a9ec9e2)

大佬，之前炸掉的那个版本能看到自动作战选项，然后现在这个版本找不到...

**Comment by wangyishenga** [comment]
> > #93
> > ![Screenshot_20240506-224337](https://private-user-images.githubusercontent.com/87552769/328218329-45cf827b-1221-4dff-9c22-31c66a9ec9e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDcwNjIsIm5iZiI6MTcxNTAwNjc2MiwicGF0aCI6Ii84NzU1Mjc2OS8zMjgyMTgzMjktNDVjZjgyN2ItMTIyMS00ZGZmLTljMjItMzFjNjZhOWVjOWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE0NDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMDExNzc0YWY5MTY4NWEwNTBhNjk3ODhjNDgxNzQ3NDk1ZDI1YjY1ZjQxNjA2Y2VkMDBjOGNlYjAwMWEzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xRLX8bijiWtA9akP8_YOMKY9XtKi2hFtNfrb-9YZEt4)
> 
> 大佬，之前炸掉的那个版本能看到自动作战选项，然后现在这个版本找不到...

难道是这个？
![Screenshot_20240506-224651](https://github.com/AegirTech/ArkLights/assets/87552769/85e2819e-81eb-4714-a16e-4e34ac28a83a)
