### ISSUE TITLE
隐秘战线模式无法正常使用

### ISSUE THREAD

**Issue by axispolari** [AegirTech/ArkLights#101]
**自查确认**
- [ YES ] 我确认当前使用了最新Release的安装包
- [ YES ] 我确认已经更新到最新版

**问题描述(必填)**
使用隐秘战线模式时，软件会在进入隐秘战线后自动重启

**复现步骤(必填)**
已有人在企鹅频道传了录像，和他的情况一模一样

**Comment by dazo6** [comment]
加一，一样的现象
