### ISSUE TITLE
debug mode 140 121

### ISSUE THREAD

**Issue by chenshan2022** [AegirTech/ArkLights#104]
**自查确认**
- [ 确定] 我确认当前使用了最新Release的安装包
- [ 确定] 我确认已经更新到最新版

**问题描述(必填)**
点了启动并定时 但是出错了

**复现步骤(必填)**

![Uploading c93912e143941f40b0519120d748f7f7.png…]()

**Comment by chenshan2022** [comment]
<img width="307" alt="c93912e143941f40b0519120d748f7f7" src="https://github.com/AegirTech/ArkLights/assets/107569384/fb3251c5-0f24-4b85-a8f1-687acc280997">

**Comment by chenshan2022** [comment]
数次重启过模拟器 无效

**Comment by Rovniced** [comment]
高级设置取消勾选 测试模式
