### ISSUE TITLE
[问题报告] 无法正常运行

### ISSUE THREAD

**Issue by moesakura** [AegirTech/ArkLights#106]
**自查确认**  
- [x] 我确认当前使用了最新Release的安装包  
- [x] 我确认已经更新到最新版

**问题描述(必填)**  
启动脚本，进去游戏界面后，一直 “游戏主页面” 和 “是否确认退出游戏之间” 循环

**复现步骤(必填)**  
启动脚本，进去游戏界面后，一直 “游戏主页面” 和 “是否确认退出游戏之间” 循环

**期望的行为**  
脚本正常运行

**截图**  
![image](https://github.com/AegirTech/ArkLights/assets/5019609/c6175c0a-78c7-45e9-9c29-ad1ebd765519)

**版本信息(必填)**  
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00  
- 主版本号:  1100
- 更新时间:  05.08 13:59

**其他内容**  
若有其他内容请写在这里

**Comment by Rovniced** [comment]
如果是手机实体机，可能是分辨率问题，请更换模拟器或者在光速虚拟内运行
