### ISSUE TITLE
无障碍选项无法打开

### ISSUE THREAD

**Issue by ryuseven47** [AegirTech/ArkLights#107]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
请尽可能详细的描述问题
点击 无障碍→arklights 按钮→弹窗
→受限制的设置：出于安全考虑，此设置目前不可用
**复现步骤(必填)**
复现此问题的详细步骤
同上
**期望的行为**
正常的情况下程序应该如何运作
正常使用App功能
**截图**
请添加相关的截图
![Screenshot_20240513-135623](https://github.com/AegirTech/ArkLights/assets/107780501/daee3464-7354-4696-9b00-4b174c18304f)

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1100
 - 更新时间: 05.13 09:50

**其他内容**
若有其他内容请写在这里

**Comment by mbdxrz** [comment]
下载一个无障碍管理器，然后没有root就再下载一个shizuku激活一下无障碍管理器 就可以给ArkLights无障碍权限了

**Comment by Rovniced** [comment]
参考此issue https://github.com/gkd-kit/gkd/issues/35
