### ISSUE TITLE
今晚更新后脚本无法正常使用，一进到宿舍换人界面就卡死

### ISSUE THREAD

**Issue by axispolari** [AegirTech/ArkLights#108]
**自查确认**
- [ √ ] 我确认当前使用了最新Release的安装包
- [ √ ] 我确认已经更新到最新版

**问题描述**
今晚更新后脚本无法正常使用，一进到宿舍换人界面就卡死，过了几秒之后就弹出日志自动退出，脚本卸载重装过后全部使用默认设置也是一样的情况

**Comment by axispolari** [comment]
补充说明，脚本唯一调过的设置为更新源切换至hotUpdate，其它均为默认设置

**Comment by Rovniced** [comment]
在高级设置内勾选 启用日志 和 保存日志到本地。之后将 /storage/emulated/0/com.bilabila.arknightsspeedrun2/log/log.txt 文件上传
![9451b4ac28896785869c7adffbdd6e8d](https://github.com/AegirTech/ArkLights/assets/52170460/11e5b2f1-928b-4ac1-a6a6-039f68affb85)

**Comment by axispolari** [comment]
这么短的日志真的能看出什么吗
[log.txt](https://github.com/user-attachments/files/15535005/log.txt)

**Comment by Rovniced** [comment]
> 这么短的日志真的能看出什么吗 [log.txt](https://github.com/user-attachments/files/15535005/log.txt)

你没勾选第一个启用日志吧？

同时勾选这2个 然后跑一遍基建

**Comment by Mudrockiii** [comment]
我也出现了同样的问题，提示：基建图标错误。好像是换发电站时候出现的。

**Comment by axispolari** [comment]
额，那个，我该怎么和你解释现在重装后直接开不了了，雷电模拟器9最新版本4核4G启用ROOT，要不你自己卸载了重装试试

**Comment by axispolari** [comment]
勾选了，两个都检查过了，然后只选了基建换班功能，跑出来的日志还是那么短，不知道为什么

**Comment by axispolari** [comment]
我把模拟器也卸载重装试试吧

**Comment by Mudrockiii** [comment]
> 我也出现了同样的问题，提示：基建图标错误。好像是换发电站时候出现的。

我刚刚也去跑了一下基建，都勾选了，日志也是很短

**Comment by Mudrockiii** [comment]
> > 我也出现了同样的问题，提示：基建图标错误。好像是换发电站时候出现的。
> 
> 我刚刚也去跑了一下基建，都勾选了，日志也是很短

好像没问题了，谢谢作者。

**Comment by axispolari** [comment]
> > > 我也出现了同样的问题，提示：基建图标错误。好像是换发电站时候出现的。
> > 
> > 
> > 我刚刚也去跑了一下基建，都勾选了，日志也是很短
> 
> 好像没问题了，谢谢作者。

问一下怎么解决的

**Comment by Rovniced** [comment]
刚刚发版修了一下 现在重新跑一遍试试

**Comment by axispolari** [comment]
> 刚刚发版修了一下 现在重新跑一遍试试

可以了，现在更新了一下跑起来了，一切正常
