### ISSUE TITLE
基建问题：宿舍换人时脚本卡住。

### ISSUE THREAD

**Issue by sirinL** [AegirTech/ArkLights#109]
**自查确认**
- [√ ] 我确认当前使用了最新Release的安装包
- [ √] 我确认已经更新到最新版

**问题描述(必填)**
运行至宿舍换人时脚本会卡住，此时无法停止脚本（点击了没有反应），但可以手动点击游戏，脚本不会抢操作，基建设施不会换人。日志
[log_120836.txt](https://github.com/user-attachments/files/15567559/log_120836.txt)

**复现步骤(必填)**
稳定复现，最近更新出现的，没有其他设置变化。更新源为hotUpdate()

**期望的行为**
[基建换人]

**截图**
请添加相关的截图

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1110
 - 更新时间: 06.04 21:24

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
这几天基建有较大更新。正在修复中

**Comment by axispolari** [comment]
同样是基建换班时发生崩溃，崩溃发生在发电站换人的时候，脚本在选择干员那里往右划了几下，然后往左滑的时候发生了崩溃，模拟器提升配置到4核6GB了也是一样的情况
[log.txt](https://github.com/user-attachments/files/15675357/log.txt)

**Comment by chenshan2022** [comment]
6月13号12点的版本更新之后基建又卡在发电

**Comment by chenshan2022** [comment]
发电站选人
