### ISSUE TITLE
开屏有长达10秒且无法跳过的广告

### ISSUE THREAD

**Issue by yexu-xuye** [AegirTech/ArkLights#11]
合鑫云真机是框架内置好的广告吗

**Comment by DazeCake** [comment]
广告为懒人精灵框架的行为，与项目无关

**Comment by moesakura** [comment]
那有考虑换个框架吗

**Comment by reKelin** [comment]
[之前](https://github.com/tkkcc/ArkLights/issues/56)也出现过这个问题并且解决了。那请问是否能利用之前的方法解决？

**Comment by wuyilingwei** [comment]
> 广告为懒人精灵框架的行为，与项目无关

Enlysure大佬还帮忙吗？

**Comment by DazeCake** [comment]
晚上出个去广告版本

**Comment by DazeCake** [comment]
框架已经自己去除广告

**Comment by 12dora** [comment]
该广告目前又出现了,推测为框架云控, 偶尔不出现的时候似乎也要等待10秒才能进去. 请求出个去广告版本

**Comment by DazeCake** [comment]
已添加去除广告版本，请使用最新版本release

**Comment by Mulsd** [comment]
能不能提供一下如何去广告的细节，想了解一下

**Comment by DazeCake** [comment]
反编译apk修改懒人框架的广告http请求结果

**Comment by mace902** [comment]
> 反编译apk修改懒人框架的广告http请求结果

能给一下url吗，我抓包只找到一个advert
