### ISSUE TITLE
基建换班问题：停在中枢换人

### ISSUE THREAD

**Issue by chenshan2022** [AegirTech/ArkLights#110]
**自查确认**
- [是 ] 我确认当前使用了最新Release的安装包
- [是 ] 我确认已经更新到最新版

**问题描述(必填)**
基建换班问题：停在中枢换人

**复现步骤(必填)**
运行到中枢换人直接结束

**期望的行为**

**截图**

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1100
 - 更新时间: 0607 08:06

**模拟器版本**
雷电9模拟器 分辨率720p

https://github.com/AegirTech/ArkLights/assets/107569384/b2974533-90d7-4f26-8da2-676cdfdfe660

**Comment by Rovniced** [comment]
高级设置勾选 启用日志 和 保存日志到本地 然后 /storage/emulated/0/com.bilabila.arknightsspeedrun2/log/log.txt 文件上传

**Comment by chenshan2022** [comment]
找到原因了 是我禁用了高产换班 抱歉
