### ISSUE TITLE
[问题报告] 无法连接到热更新服务器

### ISSUE THREAD

**Issue by Ohihahaha** [AegirTech/ArkLights#111]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
无法连接到热更新服务器,好像昨天还是可以的,现在不行了

**版本信息**
 - 主版本号: 1100
 - 更新时间: 0416 22:03

**Comment by DazeCake** [comment]
热更服务器机房断电，在处理了
