### ISSUE TITLE
[基建问题] 宿舍基建更换

### ISSUE THREAD

**Issue by chenshan2022** [AegirTech/ArkLights#112]
**自查确认**
- [ 是] 我确认当前使用了最新Release的安装包
- [ 是] 我确认已经更新到最新版

**问题描述(必填)**
基建运行还是会卡在第一个发电站换人

**复现步骤(必填)**
基建运行到第一个发电站换人，选人的时候跳基建换版结束

**期望的行为**
俩个版本之前能正常运行

**截图**
![image](https://github.com/AegirTech/ArkLights/assets/107569384/d851f9f7-4c37-4dd4-b336-007d6e528998)

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1100
 - 更新时间: 1614

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
测试功能里面勾选上 不使用ocr

**Comment by chenshan2022** [comment]
> 测试功能 勾选上 驱动ocr
感谢 能行了

**Comment by chenshan2022** [comment]
> 测试功能勾选上驱动ocr

感谢
