### ISSUE TITLE
没有详细使用文档例如如何自动培养

### ISSUE THREAD

**Issue by AMWss** [AegirTech/ArkLights#115]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
无法在github以及所提供的所谓论坛找到相应使用文档，无法正常调用自动培养，如果官方文档并不完整为什么不开放任何交流群供用户交流研究

**复现步骤(必填)**
无

**期望的行为**
完善使用文档，或开放官方用户交流群

**截图**
无

**版本信息(必填)**
 - 主版本号: 最新
 - 更新时间: 4月

**其他内容**
无

**Comment by Rovniced** [comment]
这个功能没有写完和测试好，交流群在GitHub组织的页面有写。

**Comment by AMWss** [comment]
好的，十分感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月4日(周日) 晚上9:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AegirTech/ArkLights] 没有详细使用文档例如如何自动培养 (Issue #115)




 
这个功能没有写完和测试好，交流群在GitHub组织的页面有写。
