### ISSUE TITLE
热更新之后无法启动了

### ISSUE THREAD

**Issue by Mudrockiii** [AegirTech/ArkLights#116]
**自查确认**
- [ ] 我确认当前使用了最新Release的安装包
- [ ] 我确认已经更新到最新版

**问题描述(必填)**
请尽可能详细的描述问题

**复现步骤(必填)**
复现此问题的详细步骤

**期望的行为**
正常的情况下程序应该如何运作

**截图**
![4fb0569cc64bf2464aba4ffd32406c9](https://github.com/user-attachments/assets/e7281ae6-c2cb-4759-a2c1-d237ac9857f9)

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 
 - 更新时间: 

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
已修复，重启脚本看看

**Comment by Mudrockiii** [comment]
> 已修复，重启脚本看看

还是不行，速通彻底关闭，再打开了，还是同样的提示。是不是修复推送还没到，我再等等？

**Comment by Rovniced** [comment]
版本是22：30的吗？

**Comment by Mudrockiii** [comment]
> 版本是22：30的吗？

现在好了，可能是才推送到吧，作者辛苦了v(～￣▽￣)～。
