### ISSUE TITLE
[问题报告] 找不到手机锁屏解锁设置的入口

### ISSUE THREAD

**Issue by moesakura** [AegirTech/ArkLights#120]
### 自查确认

- [X] 我确认当前使用了最新Release的安装包
- [X] 我确认已经更新到最新版

### 问题描述

找不到手机锁屏解锁设置的入口

### 复现步骤

之前是有这么个配置的，昨天点开助手之后一直白屏，所以就清理了app的缓存和配置
在设置里面找了一圈都没有找到.. 也有可能是太隐蔽了

### 版本信息

1100 11.06 13:32

**Comment by Rovniced** [comment]
哦 这个功能感觉一直没人用，也不知道能不能用，之前把进入按钮移除了，等会我再加上去吧

**Comment by moesakura** [comment]
> 哦 这个功能感觉一直没人用，也不知道能不能用，之前把进入按钮移除了，等会我再加上去吧

好的，应该是能用的（我一直在用，哈哈哈哈），感谢大佬。

**Comment by Rovniced** [comment]
已经加回，在高级设置内最上面
