### ISSUE TITLE
手机上基建换班会一直卡在基建界面，并不断提示“请再滑一次”

### ISSUE THREAD

**Issue by reKelin** [AegirTech/ArkLights#15]
**问题描述**
在手机导航方式选择手势的情况下，勾选基建换班、制造加速和线索交流等需要点击具体基建设施的时候会卡在基建主界面，并且系统会不断提示“请再滑一次”。
在手机导航方式选择其他模式的情况下，则会直接卡在基建主界面。
模拟器上没有上述问题。

**复现步骤**
手机导航方式选择手势模式，勾选基建换班、制造加速和线索交流等需要点击具体基建设施的项目，启动脚本。

**截图**
![S30905-04283302](https://files.catbox.moe/h8cjly.png)

**版本信息**
 - 主版本号: 1020
 - 更新时间: 8.26-22:46

**Comment by DazeCake** [comment]
1020版本并非本仓库维护的版本

**Comment by reKelin** [comment]
1003 09.05版本一样有这个问题

**Comment by DazeCake** [comment]
[原因](https://github.com/AegirTech/ArkLights/issues/16#issuecomment-1706329818)
