### ISSUE TITLE
轮次作战没有把理智刷完

### ISSUE THREAD

**Issue by Morris-Lucifer** [AegirTech/ArkLights#16]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
从大前天开始突然无法正常重复刷关卡，有时只刷了一次，有时一次都没有，有时则是理智没刷完，应该是在点击完关卡名后进行理智判断出现了问题，卡在那个界面许久，然后就返回大厅了，log中也没有报错

**复现步骤(必填)**
填入关卡名如1-7，勾选轮次作战，点击启动

**期望的行为**
正常情况应该刷1-7直至理智不够才会停止

**版本信息(必填)**
 - 主版本号: 1003
 - 更新时间: 09.01 21: 29

**Comment by DazeCake** [comment]
日志有显示什么吗

**Comment by Morris-Lucifer** [comment]
> 日志有显示什么吗

![Screenshot_2023-09-05-08-31-07-612_com.hypergryph.arknights.jpg](https://github.com/AegirTech/ArkLights/assets/54257509/4f6b1265-5814-4bd0-8508-b4491c571ed5)

这是脚本自动停下后的状态，感觉看不出什么…

**Comment by DazeCake** [comment]
这个分辨率可能存在问题，请优先使用720p/1080p的设备，这两个分辨率会优先支持，因为缺少人员维护，以后可能不会再对其他分辨率做支持

**Comment by Morris-Lucifer** [comment]
> 这个分辨率可能存在问题，请优先使用720p/1080p的设备，这两个分辨率会优先支持，因为缺少人员维护，以后可能不会再对其他分辨率做支持

我的设备是小米10，应该是2340x1080的分辨率，刚刚卸载重新下了游戏，待会再看看还有没有问题

**Comment by yexu-xuye** [comment]
华为也有类似的问题，现在的真机分辨率基本上都是像这种长屏幕，并且真机自带陀螺仪感应，关卡图标位置发生了偏移。我个人是采用反复启动脚本或者反复旋转手机屏幕来解决

**Comment by Morris-Lucifer** [comment]
> 华为也有类似的问题，现在的真机分辨率基本上都是像这种长屏幕，并且真机自带陀螺仪感应，关卡图标位置发生了偏移。我个人是采用反复启动脚本或者反复旋转手机屏幕来解决

原来还可以这样解决吗

**Comment by wuyilingwei** [comment]
> 华为也有类似的问题，现在的真机分辨率基本上都是像这种长屏幕，并且真机自带陀螺仪感应，关卡图标位置发生了偏移。我个人是采用反复启动脚本或者反复旋转手机屏幕来解决

这里推荐较新机型970及以上的开虚拟机，光速和vmos都可以，分辨率设置720P
