### ISSUE TITLE
[问题报告] 最新版本现在不能刷活动了吗？

### ISSUE THREAD

**Issue by by-justin** [AegirTech/ArkLights#18]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
Arklights release v1.03, 作战关卡填写 hd-6 勾选轮次作战不会进入最新的 cv-6 活动关卡。填写其他关卡名正常运行。如果只填写 hd-6 的话会直接跳过轮次作战，开始收取理智以及管理基建。

环境为 4.65_720p_Galaxy_Nexus_API_30, 720p 分辨率，CV 活动之前所有活动均未出现此状况。

Log 显示“限时活动 2”.

**复现步骤(必填)**
正常打开虚拟机，

**期望的行为**
刷活动关卡。

**截图**
![image](https://github.com/AegirTech/ArkLights/assets/73123028/00a74421-7e98-4d27-a864-a7b921dd0c1a)
<img width="785" alt="image" src="https://github.com/AegirTech/ArkLights/assets/73123028/ce34dee3-4139-4079-adff-bed056d38ae2">

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1003
 - 更新时间: 21:29

**其他内容**

#10

**Comment by DazeCake** [comment]
活动截止日期设置错了，已修复，将通过热更新自动分发至终端，无需额外操作
