### ISSUE TITLE
[问题报告] 能否再release中添加64位的版本

### ISSUE THREAD

**Issue by xvzhenduo** [AegirTech/ArkLights#19]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
能否再release中添加64位的版本，pixel不兼容32位应用无法安装

**Comment by DazeCake** [comment]
懒人框架不支持别的打包，可以尝试在虚拟机内运行
