### ISSUE TITLE
基建图标数据异常导致基建排班错误

### ISSUE THREAD

**Issue by 0linyux** [AegirTech/ArkLights#2]
![Screenshot_2023-08-28-02-09-47-79_ea3ba98994ef177df9f34376487dc7a7](https://github.com/AegirTech/ArkLights/assets/143344521/521a1ab5-a4b2-46c8-9dac-8219bd56c4da)
![Screenshot_2023-08-28-00-52-02-13_e24760d1d02f1ef481aac80648200a09](https://github.com/AegirTech/ArkLights/assets/143344521/6adafa83-be84-455d-a8a3-52c3bc226954)
![Screenshot_2023-08-28-01-02-36-02_e24760d1d02f1ef481aac80648200a09](https://github.com/AegirTech/ArkLights/assets/143344521/4d8b06d9-5061-4d81-84df-e9f6918fef8e)

**Comment by DazeCake** [comment]
图标数据引用错误，已更新
