### ISSUE TITLE
定时任务唤醒后卡在广告界面无法执行

### ISSUE THREAD

**Issue by 12dora** [AegirTech/ArkLights#20]
**自查确认**
- [ 是 ] 我确认当前使用了最新Release的安装包
- [ 是 ] 我确认已经更新到最新版

**问题描述(必填)**
设置定时任务后, 手机下次唤醒无法正常执行. 手动开屏后观察到卡在合鑫云手机广告倒计时界面. 推测不是屏幕超时熄屏导致, 屏幕超时时间已改为10分钟
原明日方舟速通repo的包并无该问题, 推测有可能是广告导致, 但无从收集线索. 

**复现步骤(必填)**
1. 设置定时唤醒任务, 长时间为佳, 如设置1小时后执行脚本. 如设置短时间后唤醒, 比如2分钟后, 大概率可以正常唤醒执行
2. 观察到没有正常执行, 开屏后卡在广告界面

**期望的行为**
正常唤醒执行

**截图**
请添加相关的截图

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1003
 - 更新时间: 

**其他内容**
设备: Google Pixel 2
系统: Android 11 官方系统(已 root) 
未设置锁屏, 点击电源键即可进桌面

之前类似的问题:
https://github.com/tkkcc/ArkLights/issues/37

**Comment by DazeCake** [comment]
已更新去除广告版本，请尝试能否复现

**Comment by 12dora** [comment]
使用无广告版问题未复现, 感谢
