### ISSUE TITLE
高产换班效率计算有问题？

### ISSUE THREAD

**Issue by reKelin** [AegirTech/ArkLights#21]
**问题描述(必填)**
当清流、温蒂、森蚺、槐琥、砾均未进驻制造站时，脚本会选择清流+槐琥+砾的组合，效率为+1.10；而实际上选择清流+温蒂+森蚺组合的效率为+1.15，更高。
当槐琥已进驻制造站/心情低于阈值时，脚本才会选择清流+温蒂+森蚺的组合。

**版本信息(必填)**
 - 主版本号: 1003
 - 更新时间: 9.10

**Comment by DazeCake** [comment]
基建部分现在处于难以维护状态，参考 #17

**Comment by reKelin** [comment]
比起普通基建，加入了搓玉的高产计算似乎问题更大，整个基建几乎全乱套了。
1. 搓玉的贸易站直接给我上了3个+20%的干员；
2. 赤金站贵金属的都没选，上了个没buff的迷迭香和精0的至简；
3. 作战记录站甚至上了个杰西卡+精0石棉+豆苗，非常抽象。

**Comment by siuze** [comment]
请问现在基建排班恢复正常了吗？我近期也发现基建全部乱套的问题，不仅是迷迭香和至简，搓玉和赤金的制造站甚至放着的是搓经验条加成的干员，而且也不会自动使用无人机加速和搓玉自动补货了，仿佛是瘫痪了一般

**Comment by Rovniced** [comment]
> 请问现在基建排班恢复正常了吗？我近期也发现基建全部乱套的问题，不仅是迷迭香和至简，搓玉和赤金的制造站甚至放着的是搓经验条加成的干员，而且也不会自动使用无人机加速和搓玉自动补货了，仿佛是瘫痪了一般

请检查分辨率是否为720或1080p

**Comment by siuze** [comment]
> > 请问现在基建排班恢复正常了吗？我近期也发现基建全部乱套的问题，不仅是迷迭香和至简，搓玉和赤金的制造站甚至放着的是搓经验条加成的干员，而且也不会自动使用无人机加速和搓玉自动补货了，仿佛是瘫痪了一般
> 
> 请检查分辨率是否为720或1080p

已再次检查确认设备分辨率为1280X720 dpi300，同时设置了强制分辨率720X1280

**Comment by Rovniced** [comment]
> 已再次检查确认设备分辨率为1280X720 dpi300，同时设置了强制分辨率720X1280

录屏一下整个过程 然后上传到这里 我看看

**Comment by siuze** [comment]
https://github.com/AegirTech/ArkLights/assets/54578647/f2d1a82e-0571-48af-87f8-575bb09c47d2

![B4C1DD3D105CADF1E78C3E428730AB5C](https://github.com/AegirTech/ArkLights/assets/54578647/f5521809-cfd3-4f26-a2a6-6549ca0f5515)


是基建的缩放步骤卡住了，每个步骤完成后都无法缩放至最小再点开制造站，卡住很久后速通只能用【进驻总览】按钮进行排班（这段没录进去），这导致它不知道制造站具体制造的素材类型，只是简单地勾选上最前面的干员。同时也导致不能用无人机和补货了

**Comment by Rovniced** [comment]
> 是基建的缩放步骤卡住了

是哪一家的云手机 还是实体机？

**Comment by siuze** [comment]
> > 是基建的缩放步骤卡住了
> 
> 是哪一家的云手机 还是实体机？

实体机 huawei p20 lite，我近期改用服务器控制MAA使用adb远程控制手机来挂机方舟了，就不再研究速通了，所以我这边这个问题可能没法再跟进。

**Comment by Rovniced** [comment]
> 实体机 huawei p20 lite，我近期改用服务器控制MAA使用adb远程控制手机来挂机方舟了，就不再研究速通了，所以我这边这个问题可能没法再跟进。

实体机运行脚本存在的问题 暂时无法修复 推荐使用模拟器或者云手机来运行
https://github.com/tkkcc/ArkLights/issues/125

**Comment by Rovniced** [comment]
基建换班已经更新，如果出现崩溃等功能在测试功能勾选 不使用ocr
