### ISSUE TITLE
[问题报告] 卡在活动界面不会进入选关卡

### ISSUE THREAD

**Issue by Dio5354** [AegirTech/ArkLights#22]
**自查确认**
- [ ✔] 我确认当前使用了最新Release的安装包
- [✔ ] 我确认已经更新到最新版

**问题描述(必填)**
活动无法自动进行作战

**复现步骤(必填)**
其余功能都能正常使用，唯独这两次活动都会卡在选择界面，不会点进活动内选择关卡，无报错。
尝试数次后会自动跳过打常规。
分辨率是720和1080都试过，效果一样。

**Comment by DazeCake** [comment]
本地测试正常无法复现此情况，请提供更详细的信息

**Comment by Dio5354** [comment]
![Screenshot_20230915-003548_arknights](https://github.com/AegirTech/ArkLights/assets/52139735/a92b98c0-7713-4013-a81d-5884bbbe3a06)

就是会一直卡在这个界面，不会点进去选择关卡的页面。这是从上次纯艾活动开始的。
自动反复尝试几次后，会跳过hd环节继续，之后一切正常。
所有设置均为默认。手机为s8

**Comment by DazeCake** [comment]
1080x2220这个分辨率可能无法支持，请考虑使用1920x1080/1280x720的设备或者使用adb命令修改分辨率

**Comment by Dio5354** [comment]
真机也没法改到这个分辨率啊，而且忽然间就活动不行这真的很诡异

**Comment by DazeCake** [comment]
可以用wm命令修改分辨率
这两次活动异常是因为阿点已经放弃维护了，现在我只能保证最低限度的更新和使用

**Comment by Dio5354** [comment]
那只能说可惜了啊，一直用的今天
😢
