### ISSUE TITLE
热更新跳过防沉迷版本后导致官服账号无法登录

### ISSUE THREAD

**Issue by LiuLi0216** [AegirTech/ArkLights#25]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包，arklights上显示是1003-09.17-21：21
- [x] 我确认已经更新到最新版

**问题描述(必填)**
我使用的是华为的nova4，分辨率是2310*1080。脚本在晚上开始清体力时，我发现脚本在输完官服账号密码，登录后，会立刻返回桌面，下方的提示信息是stop 防沉迷跳过。推测是登录时的背景由白转黑时导致误判，但b服登录并没有这种情况。

**复现步骤(必填)**
登陆官服账号就会出现。

**截图**
![微信图片_20230918004726](https://github.com/AegirTech/ArkLights/assets/114175458/190b49bf-23b9-4f8d-baad-bf6e4db46017)
![微信图片_20230918004738](https://github.com/AegirTech/ArkLights/assets/114175458/fed793fa-a0dd-4046-9ea3-e87c5d174b0b)
![微信图片_20230918004744](https://github.com/AegirTech/ArkLights/assets/114175458/06e230eb-251e-438e-8657-255d0713eca0)

**版本信息(必填)**
 - 主版本号: 1003
 - 更新时间: 09.17-21:21

**Comment by LiuLi0216** [comment]
更新到最新release的去广告版，还是有上述情况

**Comment by DazeCake** [comment]
@Mayfly777w

**Comment by Mayfly777w** [comment]
修了

**Comment by LiuLi0216** [comment]
谢谢，我去试试

**Comment by DazeCake** [comment]
还没merge呢（
@Mayfly777w 有冲突，来solve一下

**Comment by Mayfly777w** [comment]
为毛我和国人说话都要开翻译器才能看懂

**Comment by Mayfly777w** [comment]
冲突解决了（

**Comment by DazeCake** [comment]
> 为毛我和国人说话都要开翻译器才能看懂

这俩词都是git的操作行为，我觉得这么用没问题

**Comment by DazeCake** [comment]
merge了，晚点推
