### ISSUE TITLE
[问题报告] 卡在更新的签到界面 2023年9月30日

### ISSUE THREAD

**Issue by github123520** [AegirTech/ArkLights#33]
**自查确认**
- [ ] 我确认当前使用了最新Release的安装包
- [ ] 我确认已经更新到最新版

**问题描述(必填)**
速通会卡在第二个弹出的签到界面
**复现步骤(必填)**
复现此问题的详细步骤

**期望的行为**
正常应该结束签到切换账号

**截图**
[https://img1.imgtp.com/2023/09/30/PR3RLVC8.png](url)

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 
 - 更新时间: 

**其他内容**
若有其他内容请写在这里

**Comment by github123520** [comment]
img1.imgtp.com/2023/09/30/PR3RLVC8.png

**Comment by Rovniced** [comment]
刚刚推了一个新版本，应该已经修复了，现在再试试吧
