### ISSUE TITLE
默认配置中关于采购中心的建议

### ISSUE THREAD

**Issue by YipKei** [AegirTech/ArkLights#34]
建议将默认的采购配置调整为：
信用多买：招募凭证  信用少买：碳 碳素 家具零件
毕竟大多数人不需要还赛博房贷，后面家具零件相关的基本不需要。同理，招募凭证对于大多数用速通的玩家来说还是对应黄票-38抽的逻辑，价值还是远超其他物品。
至于加急凭证，我个人不需要，但不清楚其他人的情况，这一条就不瞎建议了。
修改后的默认值应该更符合更多玩家的需求。

**Comment by DazeCake** [comment]
优先购买招募凭证或许是个不错的提案，我们可以进行一个投票来确认他到底要不要并入主分支，但是家具零件设置为少买可能不太合理，不应当假定所有玩家都不需要家具零件，区别于碳素，家具零件是一个持续性可以获得收益的代币种类，而碳素在开完基建后则完全没有用处，我认为其作为默认项主动少买有待商榷。

**Comment by DazeCake** [comment]
请使用GitHub emoji表态这条评论
![image](https://github.com/AegirTech/ArkLights/assets/41264818/7e013834-3d6b-4787-8b02-ae1d6b402e6a)
来支持或反对将`招募凭证`作为信用商店优先购买的默认项目
若存在超过10个支持emoji此提案将被合并至主分支和热更新服务器

**Comment by wuyilingwei** [comment]
> 优先购买招募凭证或许是个不错的提案，我们可以进行一个投票来确认他到底要不要并入主分支，但是家具零件设置为少买可能不太合理，不应当假定所有玩家都不需要家具零件，区别于碳素，家具零件是一个持续性可以获得收益的代币种类，而碳素在开完基建后则完全没有用处，我认为其作为默认项主动少买有待商榷。

另外就材料而言，土和装置也应当为优先的，这二者都可作为搓玉原料且为信用可买中极易短缺的材料

而加急许可在几乎所有情况下均为溢出状态，尤其是使用速通一天消耗4~12张许可的情况下

最终优先：招募凭证 土 装置

最终不买：加急许可 碳 碳素

**Comment by wuyilingwei** [comment]
我的观点仅限于小范围统计，可能比较主观，统计范围从开服号到最近创号1年，各种定位的十数个账户均相似出以上趋势

**Comment by DazeCake** [comment]
不购买加急许可我认为是不太合理的，加急许可可以看作是一种快速出产黄票的方式，在缺少一定数量的黄票的情况下使用加速招募来获取黄票是一种很合理的用途，对于不搓玉的玩家来说土和装置的优先度似乎没有那么高，或许手动来添加比较合理。
话虽如此，其实在好友位拉满且普遍活跃的情况下，每天的信用点数基本上都可以买完商店

**Comment by wuyilingwei** [comment]
> 不购买加急许可我认为是不太合理的，加急许可可以看作是一种快速出产黄票的方式，在缺少一定数量的黄票的情况下使用加速招募来获取黄票是一种很合理的用途，对于不搓玉的玩家来说土和装置的优先度似乎没有那么高，或许手动来添加比较合理。 话虽如此，其实在好友位拉满且普遍活跃的情况下，每天的信用点数基本上都可以买完商店

呃，材料很主观，但是加急在使用速通的情况下我观察平均一天能吃6~8招聘许可（6/8小时一次），实际上并没有剩的招聘许可可以拿来加急（

**Comment by hotaru-hoshizora** [comment]
> 不购买加急许可我认为是不太合理的，加急许可可以看作是一种快速出产黄票的方式，在缺少一定数量的黄票的情况下使用加速招募来获取黄票是一种很合理的用途，对于不搓玉的玩家来说土和装置的优先度似乎没有那么高，或许手动来添加比较合理。 话虽如此，其实在好友位拉满且普遍活跃的情况下，每天的信用点数基本上都可以买完商店

实际上考虑到经济价值上，白票自然使用会以*相对固定*的转化比例换取黄票，加急许可仅仅是节省了等待时间（博士时间），对于材料价值的增加没有帮助。
（实际上，[NGA社区就有一个内容相当足够的关于加急许可的讨论](https://ngabbs.com/read.php?tid=21714725) ）
而等待时间的问题，只要开始运行脚本，即使每日一收的速度也能保证白票的积压数量是持续下降的；既然白票在运行期间会自行转化，那在有每日/每周任务和部分活动持续提供产出的前提下，不需要信用商店换取加急许可。

而临时加急搓黄票的用户，新手的积累时间很短，信用买加急许可的性价比太低，也因为时间不足难以解决困境；而遭遇次数不少的老玩家是不是更需要从用户自身分析一下自己是否需要一些措施避免再次需要紧急搓黄票的情况了...?

综上所述，加急许可在默认配置也足够进入优先不买的选项，如果真的有需要，他们也可以按家具零件手动添加进优先不买的方式来对加急许可进行移出优先不买的操作。

（这里鞭一下碧蓝航线，建造材料（招募材料：魔方）和加速工具（钻头）的日常获取比例是1.x：1，但目前的主要建造方案的消耗是2：1，这导致大部分玩家群体（非重氪，非爆肝以外的大部分玩家）在任何情况下钻头必定且永远溢出；这甚至没有考虑另一个更重要的建造资源（物资）

**Comment by wuyilingwei** [comment]
我们按照普通玩家计算（忽略新手任务），一个月绿票买完是30，签到是5，每天任务1x30，周常10x4.5，稳定来源110，商店按一天两张2x30，其他来源记一个月40（实际上根本达不到，因为活动不可能送这么多，基本10张一次顶天了），合计210张/月，一天也就是210/30=7张，不到两次；加急许可一天一张，外加签到5，一个月35张，实际上日均消耗有6张招聘许可即可。

而一次保底招募都是4张，也就是只需要1.5次。假设全部使用速通托管，可分为以下三种主要情况：8小时一清的情况下应当是两天三次，如果为6/12小时则为一天一次，实际上应当消耗完还有还有不少缺口。

所以我认为购买加急许可是不合理的，黄票产出是绑定的是招聘许可，而非加急许可，加急许可只是在没有一天两招的咸鱼玩家拿来冲锋的，而完全的速通用户至少是一天两清的，如果每天两清根本不会有超过50的许可，此种情况下如果需要紧急招聘，以往余下的和每日的加急完全可以cover，如果为6/12小时一清，反而每个月还有大约60~80的招募缺口。

装置和土是我考虑的不周全，但是加急我认为确实是不需要的

@DazeCake 
> 不购买加急许可我认为是不太合理的，加急许可可以看作是一种快速出产黄票的方式，在缺少一定数量的黄票的情况下使用加速招募来获取黄票是一种很合理的用途，对于不搓玉的玩家来说土和装置的优先度似乎没有那么高，或许手动来添加比较合理。 话虽如此，其实在好友位拉满且普遍活跃的情况下，每天的信用点数基本上都可以买完商店

**Comment by DazeCake** [comment]
感觉意见都不是很统一，但是似乎关于碳和招募凭证大家都比较认同作为默认项，如果投票通过的话就把这两项作为默认项吧，其余的交给用户自己配置好了

**Comment by yexu-xuye** [comment]
1.买加急许可完全没必要，如果每天公招的话，招募许可就会经常处于亏空的状态。
2.至于家具零件，就算是每期活动的限定家具都购买的话，多余的家具也是非常多的。
3.土块和装置相比于其他开服材料依旧很有用处，优先级也高一点
总结：土块、装置和招募许可优先购买，碳素、家具零件和加急许可禁止购买
