### ISSUE TITLE
希望能够支持刷10-13章节

### ISSUE THREAD

**Issue by Paker-bilibili** [AegirTech/ArkLights#36]
**自查确认**
[✔] 我确认当前使用了最新Release的安装包
[✔] 我确认已经更新到最新版

**问题描述(必填)**
希望能够支持刷10-13章节，麻烦了大佬

**复现步骤(必填)**
之前可以刷10章的图，游戏更新后无法使用，例如 
![image](https://github.com/AegirTech/ArkLights/assets/76876176/49e03787-854c-4720-ad50-1e8cfeec634f)
刷去到剿灭，在运作到刷10-3图找不到图，运作到13-3时直接进行跳过

**期望的行为**
正常的情况下程序应该正常刷去对应的关卡

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1003
 - 更新时间: 10.09-22:30

**其他内容**
设备分辨率720*1280

**Comment by Rovniced** [comment]
主线导航已修复
