### ISSUE TITLE
可以修一下当期剿灭吗

### ISSUE THREAD

**Issue by baodin0** [AegirTech/ArkLights#39]
刷关写当期剿灭从来没打过，只能刷老剿灭吗

**Comment by Rovniced** [comment]
> 刷关写当期剿灭从来没打过，只能刷老剿灭吗

请提供录屏（从脚本启动开始）和完整的复现过程，我这无法复现

**Comment by baodin0** [comment]
https://github.com/AegirTech/ArkLights/assets/114737414/3edd8644-7c2f-49f9-b662-80596abd7960

**Comment by baodin0** [comment]
https://github.com/AegirTech/ArkLights/assets/114737414/60da7036-c5ba-46cf-a04b-46dac315d23e

**Comment by baodin0** [comment]
如果我输入龙门市区他还会进剿灭看有没有打满，写当期剿灭则直接跳过。是我输入有问题吗

**Comment by Rovniced** [comment]
> 如果我输入龙门市区他还会进剿灭看有没有打满，写当期剿灭则直接跳过。是我输入有问题吗
> 

写 **当期委托** 或者 **dqwt**

https://arklights.pages.dev/guide.html#%E4%BD%9C%E6%88%98%E5%85%B3%E5%8D%A1%E6%80%8E%E4%B9%88%E8%AE%BE%E7%BD%AE

**Comment by baodin0** [comment]
原来是输入问题，感谢解答
