### ISSUE TITLE
无法启动无障碍服务

### ISSUE THREAD

**Issue by SZCDSB** [AegirTech/ArkLights#40]
**自查确认**
- [ ✓ ] 我确认当前使用了最新Release的安装包
- [ ✓ ] 我确认已经更新到最新版

**问题描述(必填)**
脚本启动后显示无法启动无障碍服务，然后脚本自动关闭重启

**复现步骤(必填)**
安装脚本，点击启动，点击确定，授权root，回到桌面，提示已经是最新版本，等待几秒后显示stop 无法启动无障碍服务，脚本悬浮窗消失，然后脚本自动重启

点开脚本设置，点打开无障碍服务，跳转到系统设置，打开脚本的无障碍服务，回到脚本设置，依旧显示无障碍服务没有打开，按返回点确定启动脚本，依然会出现问题
**期望的行为**
脚本正常启动

**截图**
请添加相关的截图

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1003
 - 更新时间: 没有弹出悬浮窗，无法确定

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
无法复现此问题，请截图完整日志或录屏完整复现流程（包括日志框内容）

**Comment by SZCDSB** [comment]
> 无法复现此问题，请截图完整日志或录屏完整复现流程（包括日志框内容）

我也复现不了了，重装了低版本能用了之后卸载重装最新版也能用来，顺便想反馈一下，使用的时候遇到了邮箱收获就停止的问题，只提示邮箱收获 停止，排了半天发现是企业微信的推送链接我多打了个换行，导致每次到截图推送的脚本就会停止，希望能在出现这个问题的时候脚本能有对应提示

**Comment by Rovniced** [comment]
已修复，变量名写错了（（（
