### ISSUE TITLE
B服换号出错导致超时

### ISSUE THREAD

**Issue by axispolari** [AegirTech/ArkLights#42]
B服在自动换号时，经常出现脚本还没点进输入账号密码的那个界面，就触发“登录被阻止，请重试”的游戏内弹窗，然后陷入无尽循环的登录失败直到“超时stop”

**Comment by Rovniced** [comment]
> B服在自动换号时，经常出现脚本还没点进输入账号密码的那个界面，就触发“登录被阻止，请重试”的游戏内弹窗，然后陷入无尽循环的登录失败直到“超时stop”

请录屏完整过程，从脚本启动开始

**Comment by axispolari** [comment]
就一直这个样子，卡在这里了
https://github.com/AegirTech/ArkLights/assets/58548635/97b17e7f-f1a0-4e4c-9d5e-6233b8848e67

**Comment by Rovniced** [comment]
> 就一直这个样子，卡在这里了 https://github.com/AegirTech/ArkLights/assets/58548635/97b17e7f-f1a0-4e4c-9d5e-6233b8848e67

多账号界面勾选`关闭当前服`，或者高级设置勾选`新版切号方案`
