### ISSUE TITLE
B服换号因网络错误二次触发图灵测试导致脚本退出

### ISSUE THREAD

**Issue by Mayfly777w** [AegirTech/ArkLights#43]
**自查确认**
我确认当前使用了最新Release的安装包
我确认已经更新到最新版

**问题描述(必填)**
请尽可能详细的描述问题
b服切号时第一次使用图鉴打码通过图灵测试后如果因为网络波动提示“请检查网络”会导致速通直接退出脚本，不会自启动需要手动再次开启
**复现步骤(必填)**
复现此问题的详细步骤
b服切号时有网络波动导致二次打码就会触发
**期望的行为**
正常的情况下程序应该如何运作
重启游戏重试当前账号
**截图**
请添加相关的截图
![image](https://github.com/AegirTech/ArkLights/assets/110718486/48f582fb-271f-4214-9a47-a8acd7211ff6)
**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1002
 - 更新时间: 10.16 23:14

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
`高级设置-启用日志` 打开此选项后截图完整日志

**Comment by Mayfly777w** [comment]
![HZ8B7R IRZKP L2RY1T3B}Y](https://github.com/AegirTech/ArkLights/assets/110718486/7582b74f-9316-4a4d-a0fd-c71a2dc63d34)
![~G7H~`053PT6CC72P N}@VI](https://github.com/AegirTech/ArkLights/assets/110718486/a59209e4-3e01-40ff-b0fa-5fecadd61aa1)

**Comment by Rovniced** [comment]
emm 复现不出来（看日志似乎是云控打码那出了问题，也许可以加一个选项来禁用云控打码）

-------

可以尝试去 `高级设置` 勾选 `新版切号方案` 来避免掉验证码（初次登陆仍需要）

**Comment by DazeCake** [comment]
增加了仅使用图鉴打码选项保证稳定性，请在高级选项中打开此选项后测试

**Comment by Mayfly777w** [comment]
已启用，我会继续开着日志，如果一天内没出错应该就解决了
