### ISSUE TITLE
[请求添加] 叙拉古复刻活动，希望增加hd定位

### ISSUE THREAD

**Issue by github123520** [AegirTech/ArkLights#47]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
请尽可能详细的描述问题

**复现步骤(必填)**
复现此问题的详细步骤

**期望的行为**
正常的情况下程序应该如何运作

**截图**
请添加相关的截图

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 
 - 更新时间: 

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
活动关卡导航已经增加，请确保脚本更新到最新
