### ISSUE TITLE
[权限咨询] 希望移除多余权限

### ISSUE THREAD

**Issue by Yanlin-Duanmu** [AegirTech/ArkLights#48]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
希望移除不必要权限

**复现步骤(必填)**
刚刚从[原仓库](https://github.com/tkkcc/ArkLights)按照提示转移到[新仓库](https://github.com/AegirTech/ArkLights)，更新后软件反复提示未授权，需要我手动授权。但我的权限和原仓库下载软件时配置的一致，未做更改。最后清除数据，发现要求强制授予**直接拨打电话**、**获取设备的定位信息**和**读写设备上的照片及文件**权限。

这让我有些困惑，一是为什么会需要这些权限呢？读写文件的权限原仓库应用并未索要也能正常更新和运行，新仓库软件也许是为了存放热更新文件所要这个权限也还能理解。但配合无障碍和悬浮权限，其余两个权限未免有些大了，而且完全看不出有用到的地方。

二是原仓库的软件并未索取这些权限，新版本的软件是增加了什么用到这些权限的新功能吗，还是懒人精灵打包时将权限也带到软件里了？

**期望的行为**
不知道是否与懒人精灵的框架有关，希望您/贵团队能够移除不必要的权限。

**截图**
![直接拨打电话权限](https://github.com/AegirTech/ArkLights/assets/68236504/20507eb3-35fd-4d4c-bacf-35a29ef9d715)
![获取设备的定位信息权限](https://github.com/AegirTech/ArkLights/assets/68236504/46095445-1d5c-469e-87e6-71d804a105e2)
![读写设备上的照片及文件权限](https://github.com/AegirTech/ArkLights/assets/68236504/1fa9c83c-a031-4824-9763-225ca1bc61b3)

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1003
 - 更新时间: 21:20

**Comment by Rovniced** [comment]
懒人精灵框架限制，明天重新传一个去除权限的版本

**Comment by DazeCake** [comment]
请阅读使用指南中的[安全性](https://github.com/AegirTech/ArkLights/blob/lr/docs/guide.md#%E5%AE%89%E5%85%A8%E6%80%A7)内容
所有权限由懒人框架索取，懒人框架闭源，我们只能保证脚本不主动收集[未声明的任何信息](https://github.com/AegirTech/ArkLights#%E6%95%B0%E6%8D%AE%E6%94%B6%E9%9B%86%E5%8D%8F%E8%AE%AE)
至于无障碍和悬浮权限都是必须的，无障碍权限用于在无root的环境下实现点击和滑动行为，悬浮窗用于显示动态UI界面和日志

**Comment by Rovniced** [comment]
https://github.com/AegirTech/ArkLights/releases/tag/v1.0.3
已增加去除多余权限的版本
