### ISSUE TITLE
[问题报告] 请在这里简要的描述问题

### ISSUE THREAD

**Issue by GenesisPanda** [AegirTech/ArkLights#50]
**自查确认**
- [ ✓] 我确认当前使用了最新Release的安装包
- [ ✓] 我确认已经更新到最新版

**问题描述(必填)**
新复刻活动叙拉古人的IS-10，用hd-10的导航无法刷取，填写hd则会直接跳过该关卡

**复现步骤(必填)**
关卡导航内填写hd-10，无法刷取IS-10

**期望的行为**
希望能添加一下hd-10的导航

**截图**
请添加相关的截图

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1002
 - 更新时间: 23:19

**其他内容**
若有其他内容请写在这里

**Comment by DazeCake** [comment]
检查是否有未点完的剧情

**Comment by GenesisPanda** [comment]
![8E144E55-031B-475B-B5ED-72466631C5F1](https://github.com/AegirTech/ArkLights/assets/142146402/1654308c-6a40-4427-82e6-45b8d5ca649d)，剧情均已点完，hd1-9都可以正常刷取，填写hd-10的时候会卡在这个地方

**Comment by Rovniced** [comment]
已修复
