### ISSUE TITLE
理智没有清完就自动结束进程

### ISSUE THREAD

**Issue by 02Alive** [AegirTech/ArkLights#51]
理智999
没有清理完就结束进程
雷电云手机前两天也是会清完才结束
999理智要反复启动三四次才能清完
版本1003 10.24 .12:00
![3TL~S1W9L)90Q85Y6XJXV7K](https://github.com/AegirTech/ArkLights/assets/105614344/df0284f2-7093-4ce8-a31e-c9d8e476c4fc)

**Comment by DazeCake** [comment]
在高级设置中禁用完全重启

**Comment by 02Alive** [comment]
问题大概清楚了，只要不用这个ui就不会出现这种问题
