### ISSUE TITLE
卡死导致超时

### ISSUE THREAD

**Issue by Yundian1** [AegirTech/ArkLights#54]
**自查确认**
- [ √] 我确认当前使用了最新Release的安装包
- [ √] 我确认已经更新到最新版

**问题描述(必填)**
卡死在主页和基建退出处导致触发超时300s报错

**复现步骤(必填)**
轮次作战时触发

**期望的行为**
程序正常运行

**截图**

![IMG_20231105_194310](https://github.com/AegirTech/ArkLights/assets/84233895/fe87d811-dc7d-49f3-9318-92e50b137748)
![Screenshot_2023-11-05-20-01-47-068_com ld dianquan](https://github.com/AegirTech/ArkLights/assets/84233895/99fb89d6-af73-4753-b848-2c3a9c84e65b)

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1003
 - 更新时间: 11.05 19:35

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
如果是雷电云手机的话，属于硬件问题，不是脚本问题
自动重启已经解决了卡死的情况，这个是预期的结果
