### ISSUE TITLE
活动八导航有时候不准确

### ISSUE THREAD

**Issue by 02Alive** [AegirTech/ArkLights#55]
最新版本
活动导航时好时坏（雷电云手机运行），有时候就是识别不出来然后放弃自动作战跳转更换基建
![导航](https://github.com/AegirTech/ArkLights/assets/105614344/8f8f5abc-2f06-4a72-9e14-b0292170d216)

**Comment by Rovniced** [comment]
从脚本点击`开始` 录屏

**Comment by Rovniced** [comment]
雷电云手机问题 #54 #59
