### ISSUE TITLE
这个app真的很好用，不知道作者需不需要赞助/打赏来帮助你长久的更新下去，我没有找到相关的联系方式，只好在这里问了，如果不合适，会删掉。

### ISSUE THREAD

**Issue by Mudrockiii** [AegirTech/ArkLights#56]
**自查确认**
- [x] #57
- [ ] 我确认已经更新到最新版

**问题描述(必填)**
请尽可能详细的描述问题

**复现步骤(必填)**
复现此问题的详细步骤

**期望的行为**
正常的情况下程序应该如何运作

**截图**
请添加相关的截图

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 
 - 更新时间: 

**其他内容**
若有其他内容请写在这里

**Comment by DazeCake** [comment]
感谢你的好意，本项目根据MIT协议开源，由[AegirTech](https://github.com/AegirTech)的成员用爱发电维护，我们并无额外的公共服务需要赞助运行，如果你希望项目能长期稳定的运行，欢迎向仓库提交代码并点上一个star，我们欢迎任何有用的pr

**Comment by Mudrockiii** [comment]
感谢你们的付出，这对没有休假的打工人有很大的帮助。我曾尝试研究过代码，但没有看懂，请问有相关教程可以推荐吗？star我已经点亮了。

**Comment by Mudrockiii** [comment]
感谢你们的付出，这对没有休假的打工人有很大的帮助。我曾尝试研究过代码，但没有看懂，请问有相关教程可以推荐吗？star我已经点亮了。

**Comment by DazeCake** [comment]
构建开发环境可以参考readme，其他问题可以加入qq交流群: 629618641
