### ISSUE TITLE
希望能有开发者维护基建排班规划

### ISSUE THREAD

**Issue by axispolari** [AegirTech/ArkLights#62]
**自查确认**
- [√] 我确认当前使用了最新Release的安装包
- [√] 我确认已经更新到最新版

**问题描述(必填)**
当前的ArkLights基建排班规划有大问题，比如会把搓玉的干员放进经验卡制造站，那么如果我使用伊比利亚审判庭来托管我的账号时，是否也会出现这种排班混乱情况

**期望的行为**
希望能有开发者维护基建排班规划，因本人没有开发软件所需的知识，即使花钱赞助或者开发者中有人愿意私人订制也是可以的

**Comment by Rovniced** [comment]
已经更新基建图标（大概修好了

有排班错误的在下面回复吧 有时间看看能不能修

设备需要保证分辨率为720或1080 帧率尽量不要低于20

**Comment by axispolari** [comment]
感谢各位开发者的辛苦维护，现在没有再见到排班混乱的情况了

以下是一点影响不算大的小问题，本人语言组织能力不太好阅读起来可能比较困难，非常抱歉

比如部分干员的基建技能需要与同阵营的干员一起进驻到同一间制造站才能有明显加成，但是在大多情况下脚本不会为这位有阵营加成技能的干员分配对应的同阵营干员到同一个制造站里面去，而是分配另外两个标准化制造技能的干员，这会导致有阵营加成技能的干员在制造站里提供的效率是微乎其微的

具体情况可以参考黑钢阵营的杏仁

**Comment by Rovniced** [comment]
> 
> 具体情况可以参考黑钢阵营的杏仁
> 


例如杏仁的2技能
> 进驻制造站时，基建内（不包含副手）每有1名黑钢国际干员（最多3名），贵金属类配方的生产力+2%，心情每小时消耗-0.15

对应的是整个宿舍内干员，速通的计算是根据单个设施进行的，无法跨设施计算（不然整个逻辑都要重写）

所以杏仁这种 涉及到跨设施的应该排除

**Comment by axispolari** [comment]
从排班名单中直接排除掉确实是最简单且有效的选择，再次感谢所有开发者对该软件的维护与付出，对于我们这些不常能触碰到电脑的玩家来说简直是救星
