### ISSUE TITLE
[问题报告] 请提供64位安装包

### ISSUE THREAD

**Issue by felinae98** [AegirTech/ArkLights#66]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
没有 arm64 的安装包
8gen3移除了支持 32 位的小核，真的运行不了这个程序了

**Comment by Rovniced** [comment]
由于懒人精灵构建的脚本在不同的版本之间有兼容性问题，故均使用的旧版本（旧版本不支持64位）。
个人有需求使用64位的可以使用新版懒人精灵自行构建。
