### ISSUE TITLE
多账号4-30不见了

### ISSUE THREAD

**Issue by mbdxrz** [AegirTech/ArkLights#67]
**自查确认**
- [✓ ] 我确认当前使用了最新Release的安装包
- [✓ ] 我确认已经更新到最新版

**问题描述(必填)**
多账号只能运行到账号3，运行不了4-30，账号4-30不见了

**复现步骤(必填)**
正常启动速通

**期望的行为**
希望能正常运行后面的账号4-30

**截图**
![Screenshot_20231209-224212](https://github.com/AegirTech/ArkLights/assets/114162295/8e95b293-f186-40d2-bbd0-2343fab1ef00)

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1002
 - 更新时间: 22:06

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
此变化主要针对于闲鱼上恶意低价卷价格的行为。
多账户变更为3个可以满足正常用户的需求。

**Comment by mbdxrz** [comment]
确实，不明白那些10r包月的怎么想的

**Comment by luanm2** [comment]
> 此变化主要针对于闲鱼上恶意低价卷价格的行为。 多账户变更为3个可以满足正常用户的需求。

能否以限制最多只允许填入三组不同的账密的形式来实现呢？
我有三个号，但是是用多账号的帐号2、3、4来刷syc，帐号5、6、7刷1-7，帐号8、9、10打剿灭，类似这样的设置，当然帐号密码都是相同的三个。这样设置可以不用根据不同的需求更改关卡设置，只需要在启用账号后面改改要刷的帐号数字就行了，结合“多帐号允许不填账密”还可以做到只运行帐号1不填帐号密码跳过重登陆阶段直接刷平时就一直登陆的大号。

**Comment by wangyishenga** [comment]
> 此变化主要针对于闲鱼上恶意低价卷价格的行为。 多账户变更为3个可以满足正常用户的需求。

我说怎么有几个号理智还是满的....一个人玩9个号有点难受（五个我的，两个妹妹的，两个朋友的），不过也可以理解就是了

**Comment by mbdxrz** [comment]
朋友你为什么有5个号

**Comment by wangyishenga** [comment]
> 朋友你为什么有5个号

开服的时候朋友安利粥，他拿自抽号让我体验，然后感觉有意思挺好玩，就又问他拿了两个自抽号（原本说是帮他玩，结果他很咸鱼，20年末这样就退坑了，最后成我的了...），那会刚开服新手期，又拿自己的手机号注册了两个...（开服过于长草）,前三年真是累，全手点，疯狂抄作业，活动奖励全打，打完帮我自己安利的同学打...不知道有脚本这东西，扔了又舍不得，如果没这脚本，别说帮别人管号，我自己可能都支持不住了，速通救我一命，基本就这样...
