### ISSUE TITLE
有收费版本吗

### ISSUE THREAD

**Issue by chenshan2022** [AegirTech/ArkLights#68]
**自查确认**
- [确认 ] 我确认当前使用了最新Release的安装包
- [ 确认] 我确认已经更新到最新版

**问题描述(必填)**
有收费版本吗

**复现步骤(必填)**
复现此问题的详细步骤

**期望的行为**
正常的情况下程序应该如何运作

**截图**
请添加相关的截图

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 
 - 更新时间: 

**其他内容**
若有其他内容请写在这里

**Comment by chenshan2022** [comment]
需求是三十个账号的使用

**Comment by Yundian1** [comment]
朋友 你为什么会有三十个账号

**Comment by chenshan2022** [comment]
> 朋友你为什么有三十个账号

所以没有针对于多账号的收费版本吗

**Comment by Rovniced** [comment]
不会有的
