### ISSUE TITLE
[功能建议] 多账号相关-希望能增加到6个账号

### ISSUE THREAD

**Issue by Jiale00** [AegirTech/ArkLights#69]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
[功能建议] 多账号相关-希望能增加到6个账号

**复现步骤(必填)**
无

**期望的行为**
[功能建议] 多账号相关-希望能增加到6个账号

**Comment by Yundian1** [comment]
朋友 你为什么会有6个账号

**Comment by Rovniced** [comment]
大部分用户数量都在3个左右，似乎没必要开放那么多
