### ISSUE TITLE
软件在MUMU12模拟器上，基建功能出现问题，无法缩放。

### ISSUE THREAD

**Issue by Billy636** [AegirTech/ArkLights#74]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
基建无法缩放，使用鼠标滚轮手动缩放，软件才会继续进程。由于是模拟器，并非是手机真机，我唯一能做的就是确认方舟的异形适配为0

**复现步骤(必填)**
打开mumu12模拟器(V3.7.5)，打开软件自动运行，随后在基建由于无法缩放（不完全缩放）卡住或导致跳过

**期望的行为**
全自动

**截图**
![image](https://github.com/AegirTech/ArkLights/assets/80997798/f9961a0e-6514-408d-b9c4-e1ae2be907fb)

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1003最新版本
 - 更新时间: 

**其他内容**
若有其他内容请写在这里

**Comment by axispolari** [comment]
建议使用雷电模拟器，我以前用MUMU的时候Arklights也会卡，换到雷电之后完美运行没出过问题

**Comment by cibimo** [comment]
我的真机k20pro也有此问题，需要手动缩小一下才能继续运行

**Comment by Rovniced** [comment]
因为目前开发测试均使用的雷电模拟器，其他模拟器没法全部测试，推荐更换模拟器解决。

**Comment by cibimo** [comment]
真机能修修吗，老是卡在那亮屏（如果说非要开电脑用模拟器那maa就够用了，想挂备用机上

**Comment by Rovniced** [comment]
> 真机能修修吗，老是卡在那亮屏（如果说非要开电脑用模拟器那maa就够用了，想挂备用机上

尝试用vmos或者光速虚拟机就行   大概下个月重写基建的时候会修

**Comment by cibimo** [comment]
> > 真机能修修吗，老是卡在那亮屏（如果说非要开电脑用模拟器那maa就够用了，想挂备用机上
> 
> 尝试用vmos或者光速虚拟机就行 大概下个月重写基建的时候会修


虚拟机的话不知道能不能定时自动唤醒，有空试试（其实能修就行，龙门币也够用

**Comment by Morris-Lucifer** [comment]
> > 真机能修修吗，老是卡在那亮屏（如果说非要开电脑用模拟器那maa就够用了，想挂备用机上
> 
> 尝试用vmos或者光速虚拟机就行   大概下个月重写基建的时候会修

请问光速虚拟机点击启动等按钮时闪退是什么原因呢？再次启动时会出现无障碍明明打开却说我没打开的情况（这种情况可以通过强行停止解决），但是闪退无法解决，设备是8gen3红魔9，虚拟ROM是安卓7
![Screenshot_20240209_022222.jpg](https://github.com/AegirTech/ArkLights/assets/54257509/671c5488-907d-4f86-bea7-8aa8d2b4bd8c)

**Comment by Rovniced** [comment]
> 请问光速虚拟机点击启动等按钮时闪退是什么原因呢？再次启动时会出现无障碍明明打开却说我没打开的情况（这种情况可以通过强行停止解决），但是闪退无法解决，设备是8gen3红魔9，虚拟ROM是安卓7

开启root权限试试

**Comment by Morris-Lucifer** [comment]
> 
> > 请问光速虚拟机点击启动等按钮时闪退是什么原因呢？再次启动时会出现无障碍明明打开却说我没打开的情况（这种情况可以通过强行停止解决），但是闪退无法解决，设备是8gen3红魔9，虚拟ROM是安卓7
> 
> 开启root权限试试
> 

试过开启root，仍然闪退

**Comment by Rovniced** [comment]
> 试过开启root，仍然闪退

https://github.com/AegirTech/ArkLights/assets/52170460/82bc90dd-c583-4d9c-8e14-991d5a7d3944

测试过似乎无问题（？

**Comment by Morris-Lucifer** [comment]
![Screenshot_20240211_094202.jpg](https://github.com/AegirTech/ArkLights/assets/54257509/4a71722a-cc2e-4c16-b596-32dae0ca3fca)
相同流程，我的光速就是不行，会不会是版本的差异？或者会员？录屏稍后上传

**Comment by Morris-Lucifer** [comment]
>  VID_20240210_115452.mp4 
> 测试过似乎无问题（？

另外就是我发现这个闪退似乎是概率触发的，只是成功启动的概率很小，有时直接点启动能成功


https://github.com/AegirTech/ArkLights/assets/54257509/d216466e-2117-4ee0-9328-51e6610c63c9
