### ISSUE TITLE
禁用训练室功能会将所有拥有训练室技能的干员都不放入宿舍，且理论上只要有五个疲劳的拥有训练室技能的干员，宿舍换班将完全失去作用

### ISSUE THREAD

**Issue by Mayfly777w** [AegirTech/ArkLights#75]
**问题描述(必填)**
禁用训练室功能会将所有拥有训练室技能的干员都不放入宿舍，且理论上只要有五个拥有训练室技能的干员，宿舍换班将完全失去作用

**复现步骤(必填)**
有五个疲劳的拥有训练室技能的干员，宿舍换班将完全失去作用

**截图**
请添加相关的截图
![image](https://github.com/AegirTech/ArkLights/assets/110718486/269e47a6-737b-4b96-9834-8c581ae76feb)

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1003
 - 更新时间: 02.02-10:46

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
这种情况似乎非常少见（晚上修修

**Comment by Rovniced** [comment]
最后总览换班的时候应该是会把剩余的宿舍全部填满的
