### ISSUE TITLE
作者你好，我想问一下能否禁用/忽略训练室更换干员？我看到设置里有忽略选项，但不起作用。

### ISSUE THREAD

**Issue by Mudrockiii** [AegirTech/ArkLights#76]
我平常会用艾丽妮进行加速，但有时候心情低，速通就直接放进宿舍休息了。我发现设置里面有相关的功能，但不知道如何正确设置才能起作用。用的是最新的雷电模拟器。
那个检测延迟改成5，似乎有用？

**Comment by Rovniced** [comment]
调高延迟就行 这个是判断的技能图标 如果设备太卡的话 可能没有检测出来
延迟改到2-3 应该就够了 改太高会影响宿舍换班效率
