### ISSUE TITLE
发现一个疑似抄袭的还拿去谋利

### ISSUE THREAD

**Issue by wyzszsdr** [AegirTech/ArkLights#77]
**自查确认**
- [ ] 我确认当前使用了最新Release的安装包
- [ ] 我确认已经更新到最新版

**问题描述(必填)**
一个叫小颜方舟的，做的很想感觉有点关系

**复现步骤(必填)**
复现此问题的详细步骤

**期望的行为**
正常的情况下程序应该如何运作

**截图**
请添加相关的截图

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 
 - 更新时间: 

**其他内容**
若有其他内容请写在这里

**Comment by DazeCake** [comment]
根据MIT开源协议，本项目并不限制商用仅保留所有权，对方官网标注了使用了仓库源码并无问题
