### ISSUE TITLE
作者您好，请问为啥我的方舟速通停止运行了

### ISSUE THREAD

**Issue by chenshan2022** [AegirTech/ArkLights#79]

**Comment by Rovniced** [comment]
刚刚有一个版本推炸了

删除掉 /data/data/com.bilabila.arknightsspeedrun2/files/script.lr
文件（使用mt文件管理器 需要root）或者直接清除掉速通全部数据

**Comment by chenshan2022** [comment]
好嘞 谢谢蛋糕哥哥
