### ISSUE TITLE
异形屏适配 连续剿灭作战

### ISSUE THREAD

**Issue by DavidHhhh** [AegirTech/ArkLights#80]
**自查确认**
- [确认 ] 我确认当前使用了最新Release的安装包
- [确认] 我确认已经更新到最新版

**问题描述(必填)**

新活动是不做异形屏适配了？ 新活动导航不了点进活动后点不到对应关卡 旧常规关卡无问题

多号（2个号）LMSQ*99受限制 只打一次就直接轮下一个作战 通过上一次作战*99可正常剿灭 高级设置里单号最大成功剿灭次数为10次

**复现步骤(必填)**

分辨率 2340X1080

**期望的行为**
正常的情况下程序应该如何运作

**截图**
请添加相关的截图

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1003
 - 更新时间: 02.21-23.58

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
某些特殊分辨率的可能导航有问题，推荐使用模拟器或者使用光速虚拟机等虚拟机运行
高级设置改了理论就应该可以多次剿灭，因为上一次的话，关卡类型不属于剿灭，所以部分判定是不受限制的
