### ISSUE TITLE
[功能建议] 强烈建议添加一个针对搬空商店的不兑换数据增补仪/条的选项

### ISSUE THREAD

**Issue by reKelin** [AegirTech/ArkLights#82]
**问题描述(必填)**
自动更新后新增并且自动勾选了搬空商店选项，搬空商店并没有将数据增补仪/条剔除在兑换范围内，导致脚本直接兑换了这两个价值几乎为0的的材料（两个材料完全被最稀少的模组块的数量所限制，多出来的部分没有任何价值）。

**版本信息(必填)**
 - 主版本号: 1003-LTS
 - 更新时间: 03.14-15:21

**其他内容**
建议默认将数据增补仪/条剔除出搬空商店的选择，或者如同信用多/少买一样添加一个文本框供用户选择并**默认少买数据增补仪/条**。

0氪玩家因为没注意突然更新了这个功能而导致商店内**有价值的物品换不完了**非常无语。

**Comment by Rovniced** [comment]
这个比较麻烦，因为商店那里没有识别物品种类。理论上每天刷活动关，是可以搬空商店的

**Comment by reKelin** [comment]
以这次活动为例，商店搬空（除无限龙门币以外的物品全部兑换）需要 6620 代币，活动任务 1290 代币，普通关卡、EX 关卡和小剿灭首通奖励 410+680=1090，总计需要消耗 357 理智。活动期间为获取所有奖励总计需要消耗 4240+357+剿灭124=4721 理智。

活动总计 14 天，自然回复理智 14*240=3360，对 0 氪玩家而言搬空商店需要额外的应急理智浓缩液 (4721-3360)/120=11.34 份，而实际上常规情况下活动期间只能囤积或获取 2\*3+1=7 份理智液，即使后置领取活动前两周的周常奖励总计获取 9 份理智药也依然不够。

而对于月卡玩家搬空商店只需要 (4721-12*300)/120=4.34 份额外的应急理智浓缩液，甚至只需要活动期间所获取的理智液就绰绰有余了。

前面一切的前提是不存在任何理智浪费的情况，包括但不限于理智溢出、突袭失败（对于攻略者来说这部分占比很大）。

如果考虑不兑换数据增补仪和数据增补条，理智液需求则会减少至 11.34-450/120=7.59 份，只需要牺牲 350 份家具零件即可搬空商店。实际上，如果所有家具套装都买一份，家具零件也只有一套多的冗余，长期不兑换活动商店的家具碎片后期可能需要花费龙门币去合成补充，之前某次活动连出2套家具的时候就已经不够过一次了。

模组数据块:数据增补仪:数据增补条消耗比为3:5:15（有些模组只开1级，模组数据块实际占比可能更高），仅仅只是挂机刷保全派驻的任务的情况下，数据增补仪和数据增补条的数量就可以溢出2倍以上。受模组数据块的限制，溢出的部分没有任何价值，兑换数据增补仪/条就是纯粹的浪费理智了。


以上结论代入到数据增补仪和数据增补条实装进活动商店后的活动商店均生效（[空想花庭讨论帖](https://nga.178.com/read.php?tid=37736788)）。

数据来源：[prts.wiki：水晶箭行动](https://prts.wiki/w/%E6%B0%B4%E6%99%B6%E7%AE%AD%E8%A1%8C%E5%8A%A8)

**Comment by rollord** [comment]
现在知道有这个功能了，零氪这么注重理智的话，可以关闭该功能，之后每次都自己手动去兑换

**Comment by reKelin** [comment]
确实也是这么做的。
只是突然有一天按照平常的习惯直接启动脚本后发现代币换了增补仪多多少少还是有些膈应的。
然后是希望添加新功能之前还是多考虑一点吧，至少可以更新后先不自动勾选新功能，让用户了解后再自行选择；只是一种建议，或许后其他更好的方式。

**Comment by Rovniced** [comment]
> 确实也是这么做的。 只是突然有一天按照平常的习惯直接启动脚本后发现代币换了增补仪多多少少还是有些膈应的。 然后是希望添加新功能之前还是多考虑一点吧，至少可以更新后先不自动勾选新功能，让用户了解后再自行选择；只是一种建议，或许后其他更好的方式。

以后新功能会改成：当多账户或者云控任务被选中，则默认打开，否则默认关闭
