### ISSUE TITLE
公开招募会把6星词条自动刷新掉。

### ISSUE THREAD

**Issue by alphanter** [AegirTech/ArkLights#83]
公开招募刷新到【高级资深干员】tag时，
会直接刷新掉该tag，并且刷新之后不会执行下一次招募。

**Comment by Rovniced** [comment]
请录屏这个过程，并且开启日志

**Comment by Rovniced** [comment]
测试了1k次公招 未出现此问题

**Comment by alphanter** [comment]
收到



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月22日(周三) 晚上7:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AegirTech/ArkLights] 公开招募会把6星词条自动刷新掉。 (Issue #83)




 
测试了1k次公招 未出现此问题
