### ISSUE TITLE
源石尘行动复刻 好像还没法打活动图

### ISSUE THREAD

**Issue by chenshan2022** [AegirTech/ArkLights#84]
**自查确认**
- [最新版本 ] 我确认当前使用了最新Release的安装包
- [最新版本  ] 我确认已经更新到最新版

源石尘行动复刻 好像还没法打活动图

**Comment by Rovniced** [comment]
去高级设置里面 把 after_require_hook 这个空改成 hotUpdate() 然后重启脚本
<img width="314" alt="59524c98e06d14d73ce17f58ab8a812f" src="https://github.com/AegirTech/ArkLights/assets/52170460/1e55f184-be13-4870-858b-948ee9d82e10">

**Comment by chenshan2022** [comment]
可以了 十分感谢
谢谢
> 去高级设置里面把after_require_hook改成hotUpdate()然后重启脚本 <img alt="59524c98e06d14d73ce17f58ab8a812f" width="314" src="https://private-user-images.githubusercontent.com/52170460/315979355-1e55f184-be13-4870-858b-948ee9d82e10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDk3NzIsIm5iZiI6MTcxMTEwOTQ3MiwicGF0aCI6Ii81MjE3MDQ2MC8zMTU5NzkzNTUtMWU1NWYxODQtYmUxMy00ODcwLTg1OGItOTQ4ZWU5ZDgyZTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEyMTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjY2ZhZWZhNmY2MDA1MmI1MGIxNjBlNTA5YzVjYzFlMmE2OWU1OTI4ZDM0YmFhNDk2YjBjMDA3MTE3OWIyYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YHI6Ob3h5HNryTG6ePNhVSdRUjjpQFc6FxQ65x3G72A">
