### ISSUE TITLE
［功能建议] 审判庭通知显示账号

### ISSUE THREAD

**Issue by longxin1234** [AegirTech/ArkLights#87]
审判庭QQ/微信通知显示账号

**Comment by Rovniced** [comment]
好像这个需求没有大的必要性？
审判庭本身就是依靠账户来搜索日志的 没必要再重复添加一个账户显示吧

**Comment by DazeCake** [comment]
没懂什么叫审判庭通知显示账号，审判的通知被设计为推送到不同的账号用户手中，不应该重复写入同一个推送对象作为admin的消息来源
