### ISSUE TITLE
[问题报告] 请在这里简要的描述问题

### ISSUE THREAD

**Issue by JG1214** [AegirTech/ArkLights#88]
战斗作战失败，使用ap，ce上一次等方法无法自动战斗

**Comment by Rovniced** [comment]
无法复现，请确保使用的是最新版本（4.7日的） 然后录屏

**Comment by JG1214** [comment]
> 无法复现，请确保使用的是最新版本（4.7日的） 然后录屏

有更新的吗，我用的还是23年的。

**Comment by JG1214** [comment]
问题已解决
