### ISSUE TITLE
[问题报告] 巴别塔活动关在点击“开始行动”前，脚本会自动跳回主页

### ISSUE THREAD

**Issue by zqfzqf** [AegirTech/ArkLights#89]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
巴别塔活动关在点击“开始行动”前，脚本会自动跳回主页，具体可见视频

**复现步骤(必填)**
使用hd-x时才有这个问题，使用syc打活动关是正常的

**录屏**

https://github.com/AegirTech/ArkLights/assets/33652938/75010d20-6bbf-49c4-b9a5-81c1736283f8

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1100
 - 更新时间: 04.18 23:36

**Comment by Rovniced** [comment]
检查测试功能是否勾选了不打三星关卡
