### ISSUE TITLE
轮替作战有问题

### ISSUE THREAD

**Issue by chenshan2022** [AegirTech/ArkLights#90]
**自查确认**
- [ 确定] 我确认当前使用了最新Release的安装包
- [确定 ] 我确认已经更新到最新版

**问题描述(必填)**
轮替作战有问题

**复现步骤(必填)**
轮替作战没法自己运行，需要手动勾选代理指挥才能开始作战，否则就会把所有图看一遍，都不打

**期望的行为**
轮替作战自己开始作战

**截图**
请添加相关的截图

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 1100
 - 更新时间: 04.18 23:36

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
检查测试功能是否勾选了不打三星关卡

**Comment by chenshan2022** [comment]
> 检查测试功能是否勾选了不打三星关卡
卧槽 这个玩意也有影响的啊

**Comment by chenshan2022** [comment]
> 检查测试功能是否勾选了不打三星关卡

感谢大佬
