### ISSUE TITLE
刚刚使用的时候他会自己吃药，但我没选择吃药

### ISSUE THREAD

**Issue by Mudrockiii** [AegirTech/ArkLights#95]
**自查确认**
- [x] 我确认当前使用了最新Release的安装包
- [x] 我确认已经更新到最新版

**问题描述(必填)**
如图所示，吃药相关的我都没有打开，但是他在没理智后，直接吃药，然后继续刷。之前没出问题，就刚刚出现的。

**复现步骤(必填)**
复现此问题的详细步骤

**期望的行为**
正常的情况下程序应该如何运作

**截图**
![ddffe6394a183eea44090b0aad4e48c](https://github.com/AegirTech/ArkLights/assets/110472431/45c3cc27-56e6-4a61-a014-54819263b954)
![592356196c6db87aee11d18bd16aa38](https://github.com/AegirTech/ArkLights/assets/110472431/23c1446b-1154-4aa3-a715-f16831856cc0)

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 
 - 更新时间: 
![815b0f9d925c10f2e979b0c248fe01b](https://github.com/AegirTech/ArkLights/assets/110472431/6467fcce-ae0f-4cec-a7a2-35a4d1d340f1)

**其他内容**
若有其他内容请写在这里

**Comment by Rovniced** [comment]
这样填写的话 理智药会在24h内过期的情况下吃

**Comment by Mudrockiii** [comment]
我手机上使用旧版本速通，没有root，也出现了自动吃药问题

**Comment by Mudrockiii** [comment]
理智药都是新的，还有6天的那种

**Comment by Mudrockiii** [comment]
好像我在作战关卡那里写（上一次）就没事，但是我这个速通，那里写了（活动7），就自己吃药

**Comment by Rovniced** [comment]
这不是写的 6天理智药最多吃一次吗 理智药剩余6天就会吃啊

**Comment by Mudrockiii** [comment]
啊？？？我瞎了，对不起对不起对不起！！！

**Comment by Rovniced** [comment]
不要让他吃药的话 在主页药水数量那改成-1就好了 这样即使24h理智药也不会吃
