### ISSUE TITLE
问题报告] 设置刷图14-8*99则无法进入作战

### ISSUE THREAD

**Issue by baodin0** [AegirTech/ArkLights#97]
**自查确认**
- [ ] 我确认当前使用了最新Release的安装包
- [ ] 我确认已经更新到最新版

**问题描述(必填)**
请尽可能详细的描述问题

**复现步骤(必填)**
复现此问题的详细步骤
设置刷图14-8*99

**期望的行为**
正常的情况下程序应该如何运作

**截图**
请添加相关的截图
![image](https://github.com/AegirTech/ArkLights/assets/114737414/942b70b9-f64e-4639-ad53-a65669737202)

**版本信息(必填)**
版本信息会显示在日志悬浮窗的绿色标题区域，主版本号为4位数字如1000，更新时间为一个时间如12:00
 - 主版本号: 
 - 更新时间: 

**其他内容**
若有其他内容请写在这里
![video22024522346322](https://github.com/AegirTech/ArkLights/assets/114737414/a2f8bb7d-09b1-4964-8634-2ffe2ee02c8f)

**Comment by Rovniced** [comment]
#90 重复issue
