### ISSUE TITLE
没有完成前面主线的进入第14章会卡界面

### ISSUE THREAD

**Issue by 02Alive** [AegirTech/ArkLights#98]
![Uploading image.png…]()

**Comment by 02Alive** [comment]
![Uploading QQ截图20240503021133.png…]()

**Comment by 02Alive** [comment]
![Uploading QQ截图20240503021133.png…]()

**Comment by 02Alive** [comment]
![QQ截图20240503021133](https://github.com/AegirTech/ArkLights/assets/105614344/066eea4f-34a8-4c27-976f-8c7fc5ffebb5)

**Comment by Rovniced** [comment]
已修复
